### PR TITLE
Fixed slow repaint for lines, fixes #751

### LINKED ISSUE #751: Stuttering when panning
When I pan the view (drag while holding right mouse button) the repainting noticeably stutters, and a single CPU core goes to 100% while the pan is ongoing. The effect seems worse when zoomed in than when zoomed all the way out, and is the same regardless whether a simulation is running or not. Disabling grid does not really improve performance much.

I did some quick profiles. Profile of when zoomed in:

image

Profile when zoomed out:

image

It seems the biggest CPU hog are the SunGraphics2D functions.
Maybe a fix would be to only draw things that are in the viewport?

Circuit used to test: https://darvit.nl/s/32-bit_RISC-V_CPU_milandamen.dig

System specs:
OS: Kubuntu 20.04
CPU: AMD Threadripper 2950x
Screen resolution: 2560x1440

### PR DESCRIPTION
**Pull request by milandamen**
This PR increases performance of #751 by around 50%.

A configuration option is added to enable the feature; by default the feature is disabled.

I did not add any test for this functionality, if you want me to do so, please point me towards where I can do so.

Currently, tests relating to language are failing because I only speak English and Dutch, so I don't know if I can create translations for other languages.
The configuration option is also added in Basic tab, and should probably be in Advanced tab instead, but I don't know how to do that.

@hneemann could you please advise?

### CODE REVIEW

**Comment by hneemann** [comment]
Something must be going really wrong on your machine. Clipping lines to the view port has been possible efficiently since the 60s. There are very elegant algorithms like the Cohen–Sutherland algorithm for this. I expect this to be completely handled by the graphics hardware. It should not be necessary to implement something for it yourself. 
That would be like implementing Bresenham's line algorithm yourself.

**Comment by milandamen** [comment]
Yeah true, though I'm only running OpenJDK 1.8 so it's nothing too special.

**Comment by hneemann** [comment]
Have you tried a newer JDK?

**Comment by milandamen** [comment]
Ah it works perfectly on OpenJDK 1.16. Seems like the older version OpenJDK 1.8 doesn't draw efficiently then.

Seems like this PR is not needed anymore, unless someone on java 8 needs it.

Thanks for the help!

**Pull request closed without merging**
