### PR TITLE
Added functionality to import SVG Files

### PR DESCRIPTION
**Pull request by cor-aurum**
Adds a new Editor for circuit properties, in which a simple SVG Import is realised. 
Note, that this doesn't mean, that Digital becomes a full-fletched SVG-Viewer.
Known restrictions: No Elliptic curves are supported within paths.
Advanced styling options are not supported. Use stroke, stroke-width, fill or font-size within the style attribute. Tested with Inkscape. Adobe Illustrator may work, too.

### CODE REVIEW

**Comment by cor-aurum** [comment]
Sorry for the huge amount of conflicting files. Most of them are not relevant

**Comment by hneemann** [comment]
But who should find out which changes are relevant? :-)
A clean pull request is more likely to be accepted.

**Comment by cor-aurum** [comment]
Sorry about that. Now there shouldn't be any conflicts. Mvn install succeed on my machine..

**Comment by hneemann** [comment]
Most of the code was transferred to the branch "polygon".

**Pull request closed without merging**
