### PR TITLE
Adds 74164

### PR DESCRIPTION
**Pull request by guiweber**

### CODE REVIEW

**Comment by guiweber** [comment]
@hneemann what is the easiest way to test the circuit? I seem to only be able to import it as a DIL package within itself. That is, if I open the .dig file in Digital then I can see it in the custom components. If I use a new circuit instead, I don't see it in the custom components. Changing the file location doesn't seem to have an effect.

**Comment by guiweber** [comment]
@hneemann what is the easiest way to test the circuit? I seem to only be able to import it as a DIL package within itself. That is, if I open the .dig file in Digital then I can see it in the custom components. If I use a new circuit instead, I don't see it in the custom components. Changing the file location doesn't seem to have an effect.

**Comment by hneemann** [comment]
@guiweber Why not add a test case to the circuit. The only things you can not test are the pin numbers.

You can only import files which are in the same folder or in a sub-folder of your actual circuit. This behavior is very simple and avoids dealing with library paths and so on. You also can zip the files, unzip them anywhere and it works. 

Maybe you should install a JDK1.8 and maven. Then you can run the tests before you commit.
Thats much easier.

**Comment by guiweber** [comment]
Thanks, it is very simple indeed. I just had my circuit in a the wrong location.

I corrected two errors with the circuit but now I'm not sure why the test is failing:
```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.44 sec <<< FAILURE! - in de.neemann.digital.integration.TestExamples
testDistExamples(de.neemann.digital.integration.TestExamples)  Time elapsed: 8.014 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<174> but was:<175>
	at de.neemann.digital.integration.TestExamples.testDistExamples(TestExamples.java:31)
```

Which would mean this line fails
```
assertEquals(174, new FileScanner(this::check).scan(examples));

```

**Comment by hneemann** [comment]
Yes, thats a bit tricky. In a former project i had trouble with test files which were deleted by a mistake and nobody noticed that.
Thince than I allways check the number of test files in the test case. 
You added a test file so you have to increase the number of files in the test case.

**Comment by guiweber** [comment]
Ah I see. Were you using git on that project? Personally I find that git makes it easy to see if any file was deleted when you review pull requests. Although it would be another story if you had a lot of people on an internal team with push privileges... but with a single or a few reviewers, the risk seems pretty low.

In any case, the counter has been incremented and it should be all good now.

**Comment by hneemann** [comment]
This happened in the dark ages when Git was not yet invented. ;-)
SVN was used and everyone could commit to the repo. There was no support for code reviews, and I'm wondering how it was possible to develop software back in the days. :-)
But you are right: Today it is more a habit, not a necessity.

**Pull request merged**
