### PR TITLE
Added 74112

### PR DESCRIPTION
**Pull request by guiweber**

### CODE REVIEW

**Comment by hneemann** [comment]
The circuit is extremely hard to understand because of keeping the pin positions close to the DIL package. Why did you do that?

**Comment by hneemann** [comment]
What do you think about such a layout:

**Comment by guiweber** [comment]
Ah yes, you are probably right. I did it like that out of habit because that's how the 74xx circuits were laid out in the Logisim library. It does make them harder to understand at a glance.

Would you like me to update my pull request or will you commit your changes?

**Comment by hneemann** [comment]
I will commit my changes. That's more easy.

**Pull request closed without merging**
