### PR TITLE
Added new Create Simple Custom Shape feature.

### PR DESCRIPTION
**Pull request by sgparry**
This adds a rectangular custom shape to the current circuit, with a pin
for each input or output, arranged similarly to the inputs outputs in
the circuit, but minimally and uniformly spaced to the grid.

### CODE REVIEW

**Comment by hneemann** [comment]
To me it feels like a bad idea to implement the generation of a new shape type in a way that this new shape is not generated on the fly. This means if the user changes the inputs or outputs of the circuit, the old shape will not match the new circuit.
I have thought about this problem and have re-factored the code for the shape selection. This makes it easier to implement different shapes for embedded circuits. And I have added a new shape type which determines the pin positions from the circuit it represents.
You can find that implementation in the newShapeType branch.

**Comment by sgparry** [comment]
I take your point - but what I needed was something that would generate a starting shape I could then customize further. This would properly belong in a custom shape editor - if we had one .

**Comment by hneemann** [comment]
You can start Digital in experimental mode (add command line argument "experimental").
Than you can add a very simple shape to the circuit which shows most of the possible graphical elements. But this shape does not depend on the circuit, so you have to add all the pins by your own.

**Comment by hneemann** [comment]
> Currently the new shape type assumes you want the pins to line up along the edges. This would be the more common use case, but I often want multiple rows of pins - for example so that I can mount an LED Hex Digit inside the rectangle for a register.

This is far to exotic to be implemented in Digital. Something like that needs to be implemented as a real custom shape. I also do not want to add a "shape generator" which generates such a shape.

But maybe it's possible to implement it as your own external program which reads a *.dig file and than adds the shape to it.

**Comment by sgparry** [comment]
I agree (2) is probably too specialized a requirement; your current implementation in the newShapeType does most of what is needed there already anyway. However, I think being able to do (1), i.e. generate a custom shape based on whatever shape type you have currently selected will be very useful for anyone wanting to create their own custom shapes - it gives a quick starting point. The real pain with hand editing from scratch is creating all the pins. I would be happy to have a go at coding it, if you were willing to include it.

**Comment by sgparry** [comment]
Would you be interested in me writing a "Copy to User-Defined Shape" feature instead? The use case for this is a user wanting to create a user-defined shape based on a standard shape (Default, simple, DIL-chip, layout, etc) :

1. User creates embedded circuit.
2. User uses Edit -> Edit circuit Attributes to choose the desired shape and color closest to the user-defined shape she s/he requires.
3. User selects either selects Edit -> Copy to User Defined Shape (or possibly clicks a "Copy to User Defined" button on the dialog or possibly this could come up as a prompt when they select User-Defined).
- The would be disabled / error if the user-defined shape type was already selected.
- If one or more In/Outputs are not labelled an error message is given and nothing changes.
- If the shape type is not supported by the copy process, an error message is given and nothing changes.
4. The standard shape and pins would then be inserted as polys, texts, pins etc within the customShape tag.
5. User saves and closes the circuit and edits the custom shape (currently by hand) to requirements
6. User re-opens the embedded circuit in Digital and uses Edit -> Edit circuit Attributes to choose User-defined shape type.
7. User saves and test the embedded circuit in the parent circuit.
In addtion, a seperate command could be coded to sync the pins in the user-defined shape with those in the circuit, removing non-matching ones and inserting new ones; this in itself would be a serious time saver.

**Comment by hneemann** [comment]
As soon as the SVG import is available, this function is obsolete. See also #39, #153

**Comment by sgparry** [comment]
How will the pins be handled in the SVG input?

On 24 August 2018 10:05:41 BST, Helmut Neemann <notifications@github.com> wrote:
>As soon as the SVG import is available, this function is obsolete. See
>also #39, #153
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hneemann/Digital/pull/178#issuecomment-415699949

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hneemann** [comment]
I plan to use the id attribute to identify pins.
An element with the ID "pin: in1" identifies the pin "in1".
But in the last few weeks I did not have enough time to work on the SVG import branch, so unfortunately there is not much progress.

**Pull request closed without merging**
