### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by maltaisn**
The translation is not fully done yet, the static documentation content is still missing. So don't merge just yet, I'm just making the pull request to let others know and avoid duplicate work (somewhat unlikely, but let's not take chances).

I also fixed a few issues with the English translation, I hope you don't mind. Mostly fixing typos and uniformizing capitalization.

There's also a fix for `TestSyntax`, I found that it failed to detect incorrect escaping of quotes in some cases. For example the test would still have passed with strings like `' '{0}` (even number of quotes before `{`) and `{0}'` (quotes after last param).

### CODE REVIEW

**Comment by hneemann** [comment]
@maltaisn 
I have created a new branch "french" which can be used to complete the French translation.

All your other suggestions, I have committed directly into master.

**Comment by maltaisn** [comment]
I just finished the static content. I'm not entirely sure I did the right thing with git here, but it should probably be mergeable.

I haven't generated the screenshots, only updated the script to add the language. I'm on Ubuntu and the title bars were pretty different from the other documentation files, so I leave that to you.

**Comment by hneemann** [comment]
@maltaisn 
I have integrated the French translation, and the latest pre-release build already contains it.
How can I give you credit in the readme file?

**Comment by maltaisn** [comment]
Thanks for merging! You can put my name (Nicolas Maltais) with my GitHub username @maltaisn, I'm not affiliated with any organization.

**Pull request merged**
