### PR TITLE
fix: 7489, 74189, add: 74175

### PR DESCRIPTION
**Pull request by coreidcc**

### CODE REVIEW

**Comment by coreidcc** [comment]
this time 'mvn validate' works

**Comment by hneemann** [comment]
Are you willing to provide the IC's with test cases? I would like to reduce the number of IC's without test cases and it seems to me that you know better about these chips than I do.

**Comment by coreidcc** [comment]
here you go. 7489, 74189 and 75175 now all have test-cases

**Comment by coreidcc** [comment]
closed as fixes doesn't seam to be of interest

**Comment by hneemann** [comment]
@coreidcc 
I finally got around to merge your changes. 
Thanks for your help and sorry for the long delay!

**Pull request merged**
